[package]
name = "libsql_function"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql_bindgen = "0.1"
libsql_wasm_abi = "0"

[lib]
crate-type = ["cdylib"]
